version: '3'
services:

    #PHP Services
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - internal

    #Nginx Services
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - internal

#Docker Networks
networks:
    internal:
        driver: bridge

